### ISSUE TITLE
Sort the keys

### ISSUE THREAD

**Issue by bscofield** [bscofield/wetcd#13]
etcd doesn't seem to return keys in a consistent order, making reloading the list after adding or removing a key a bit disconcerting.

**Comment by xiang90** [comment]
@bscofield Hrm... In fact we are going to deal with all these sort of things. Recursively get, sort get etc..

**Comment by bscofield** [comment]
That'd be wonderful -- I'll yank the post-retrieval sort here once that functionality is in etcd itself.
