### ISSUE TITLE
Looks like they go rid of the etcd dashboard module. 

### ISSUE THREAD

**Issue by nightwolfzor** [bscofield/wetcd#15]
Is this project still live as there is no longer an etcd dashboard

**Comment by bscofield** [comment]
Ah, I didn't realize they'd pulled it out -- I haven't used etcd for quite a while as I changed jobs, etc., so I haven't been keeping up. For the same reason, once I heard that they'd integrated a dashboard module I stopped working on this, so it's pretty unlikely it'd work with a current etcd install. Have you looked at https://github.com/AdoHe/etcd-dashboard?

**Comment by nrshrivatsan** [comment]
@bscofield the link you shared is cool!  Really helps!
