### ISSUE TITLE
Only show "Loading" when we're actually loading keys

### ISSUE THREAD

**Issue by bscofield** [bscofield/wetcd#8]
It shows up when a prefix is empty, f'rinstance.

**Comment by xiang90** [comment]
@bscofield 
great work!
feel free to ask any web api support you may want/need. I am working on designing json statistic data interface.

**Comment by bscofield** [comment]
Thanks, @xiangli-cmu -- I think CORS is sufficient for now (unless you wanted to add a call that would return the entire contents of a prefix path without walking the directory keys individually :)

**Comment by bscofield** [comment]
All mentions of "Loading" are gone now.
